services:
  my_postgres:
    image: postgres:13
    container_name: postgres_trainy
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_service
    working_dir: /app
    ports:
      - '3001:3001'
    depends_on:
      - my_postgres
    environment:
      DATABASE_URL: postgresql://my_user:my_password@my_postgres:5432/my_database?schema=public

volumes:
  postgres_data: